### ISSUE TITLE
CNAME removal

### ISSUE THREAD

**Issue by josefzacek** [gsamokovarov/middleman-gh_pages#1]
Thank you very much for this great gem

The problem I have is that everytime I run `middleman gh_pages`, I need to go back to gh-pages branch on GitHub and create new CNAME file as I'm using custom domain name

**Comment by gsamokovarov** [comment]
@josefzacek, sorry for the really late reply. Didn't watch the repo, so I didn't get a notification. 🙁 Did you solve your problem, are you still using this gem?

**Comment by josefzacek** [comment]
@gsamokovarov, I'm using gem 'middleman-deploy', '~> 2.0.0.pre.alpha' now because lack of response from your side especially when https://github.com/gsamokovarov/middleman-gh_pages/issues/2 issue arrised.

CNAME issue in gem 'middleman-deploy', '~> 2.0.0.pre.alpha' is solved by putting CNAME in source folder. This could work for your gem as well but I did not test it.

**Comment by gsamokovarov** [comment]
Yeah, sorry for that. The same solution works for this gem as well. Here is an example project that uses `middleman-gh_pages` with a `CNAME` in the `source` folder: https://github.com/euruko/euruko2016.github.io/tree/master/source.
