### ISSUE TITLE
0.8.0 is pusshing to gh_pages branch rather than gh-pages branch

### ISSUE THREAD

**Issue by josefzacek** [gsamokovarov/middleman-gh_pages#2]
update to version 0.8.0 is pushing to **gh_pages** branch rather that **gh-pages** branch

![screen shot 2018-03-11 at 23 31 48](https://user-images.githubusercontent.com/2744855/37259925-e40a85a2-2584-11e8-9e6e-6ce46c3811af.png)

**Comment by gsamokovarov** [comment]
Thanks for spotting this and sorry for the late reply. Will fix it and release 0.9.0 in a bit.

**Comment by gsamokovarov** [comment]
I have merged the fix for this in `0.9.0`. Thank you for the report and @akarzim for the fix! 🙇‍♂️
